### ISSUE TITLE
V113 無法破攻

### ISSUE THREAD

**Issue by gksd55377** [reanox/MapleStory-v113-tool#11]
以編譯成功 改成113
實際測試無法破攻

**Comment by D363N6UY** [comment]
預設remove cap是註解的，有開啟嗎?

**Comment by gksd55377** [comment]
發現是maplestory.exe的問題,改原版後可破功
WIN7可正常運作 WIN10會出現找不到ijl15.dll錯誤

**Comment by gksd55377** [comment]
調整編譯環境後已成功!!
