### ISSUE TITLE
How to contact the author

### ISSUE THREAD

**Issue by fmnijk** [reanox/MapleStory-v113-tool#16]
請問有作者您的信箱之類的可以聯繫嗎

**Comment by D363N6UY** [comment]
Hi, 您好，這個專案已經很久沒有更新，而且我也很久沒有在這塊領域研究，您有什麼需要或許我可以幫忙，但幫助也有限

**Comment by fmnijk** [comment]
我希望這個專案可以支援v122，我願意付費請您幫忙

**Comment by fmnijk** [comment]
@reanox 不知道這樣會不會有通知
